apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-test-app
  name: nodejs-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-test-app
  template:
    metadata:
      labels:
        app: nodejs-test-app
    spec:
      containers:
        - image: quay.io/openshift-pipeline/vote-api:latest
          imagePullPolicy: Always
          name: nodejs-test-app
          ports:
            - containerPort: 9000
              protocol: TCP