apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-ex-git-00001-deployment
  name: nodejs-ex-git-00001-deployment
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: nodejs-ex-git-00001-deployment